### ISSUE TITLE
Menu icon wrapping incorrectly

### ISSUE THREAD

**Issue by hayleyorndorf** [qubeshub/supertemplates#5]
In minimized windows, items at the end of the menu are wrapping below the first menu item. At first glance  the items seem to have disappeared. Upon hover, the item is there, but with white text on a white page. 

Screenshots in UX QUBES Project

**Comment by mdlama** [comment]
![screen shot 2018-01-22 at 12 16 37 pm](https://user-images.githubusercontent.com/4877315/35234165-2c9e9156-ff6e-11e7-9e77-23cc0b39c0f0.png)

**Comment by mdlama** [comment]
Thanks, Hayley!  Indeed, it is different from Issue #1.

**Comment by mdlama** [comment]
Fixed by 4ab9f6a
