### ISSUE TITLE
Sidebar is jumpy on scroll

### ISSUE THREAD

**Issue by mdlama** [qubeshub/supertemplates#7]
See https://qubeshub.org/community/groups/aims

Jenny, do you notice this?  I tried taking a video but it must be at the same refresh rate cuz it isn't showing the jumpiness.

**Comment by trisketz** [comment]
I went to their group and I see what you're talking about. I'm looking into the cause.

**Comment by trisketz** [comment]
Found the issue, bad selector on my part in identifying the media query. Changed the selector and looks to be fixed on AIMS. I put in a pull request for the correction.

**Comment by mdlama** [comment]
Awesome, thanks, Jenny!
